### PR TITLE
Update vm's port's tags only if they are different

### PR DESCRIPTION
**Pull request by kytomaki**
Port tags should not be updated if they are identical.

### CODE REVIEW

**Comment by annakhm** [comment]
Hi @kytomaki, was your motivation to reduce unneeded roundtrips when the other attribute (vm tag) changes? In this case, please consider using d.HasChange terraform indicator instead.

**Comment by kytomaki** [comment]
The problem manifested when running `terrafom destroy` on the resources with limited user. Problematic function is `resourceNsxtVMTagsDelete` which tries to delete vm's port's tags. The user in question didn't have privileges to alter the port.

https://github.com/kytomaki/terraform-provider-nsxt/blob/cd802f26993c5ad4d23acf8474a4bd29bddb7bb9/nsxt/resource_nsxt_vm_tags.go#L295-L297

So this is a bit of a workaround to get past that.

**Comment by annakhm** [comment]
Thanks for the explanation @kytomaki, I think same workaround behavior would be achieved during deletion if we don't execute updateTags in case provider doesn't have any tags defined in schema. For update case, d.HasChange would do the job of avoiding unnecessary update. This approach seems simpler to me - would you agree? I can file a PR with this change if you prefer.

**Comment by annakhm** [comment]
I'm suggesting to fix this with https://github.com/terraform-providers/terraform-provider-nsxt/pull/261

**Comment by kytomaki** [comment]
Thank you so much the #261 seems to work perfectly! I'll close this :)

**Pull request closed without merging**
