### PR TITLE
Migrating to the Terraform Plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrating to the Terraform Plugin SDK using the automated migration
tool. Build and tests pass.

### CODE REVIEW

**Comment by annakhm** [comment]
Hi @lazzurs, thanks for this PR! 
We are planning a significant provider expansion in coming weeks, and it order to avoid merges, we'd rather migrate to to the sdk a bit later.

**Comment by lazzurs** [comment]
@annakhm I can understand that and had a similar issue with another provider. I am happy to either leave this open so I can update it when the changes have happened or close it and I can watch your provider for a new release and re-create then?

**Comment by annakhm** [comment]
@lazzurs I'm happy to keep it open for now. Hopefully this will be resolved soon.

**Comment by annakhm** [comment]
Hi @lazzurs,
We've landed the big commit, and it was easier to run the upgrade tooling from scratch on the extended repo. I opened another PR for migration https://github.com/terraform-providers/terraform-provider-nsxt/pull/210, thus closing this one. Thanks again for the effort!

**Pull request closed without merging**
