### PR TITLE
Support for LogicalRouter FirewallSection and LogicalRouterPort Rule

### PR DESCRIPTION
**Pull request by fdhex**
EdgeFirewall sections cannot currently be edited due to lack of support for LogicalRouter applied_to sections. In a similar way, it is not possible to create a rule within a edge firewall section that applies to only a LogicalRouterPort.

Both are within /firewall/sections and can be updated using same API as DFW rules so there should be no reason the provider can't be used for them.

### CODE REVIEW

**Comment by fdhex** [comment]
@asarfaty I have updated the list of options in the firewall_section documentation

**Comment by fdhex** [comment]
@asarfaty is there anything else you would need?

**Comment by annakhm** [comment]
Hi @fdhex, thanks! We'll need to run a few tests for this change. We can acceptance tests as follow up.

**Comment by fdhex** [comment]
@annakhm Have you had the chance to run the required tests?

One problem is the impossibility of deleting the default rule of an EFW but the API can be used to CRUD anything else on the EFW.

**Comment by annakhm** [comment]
Hi @fdhex, unfortunately we didn't cover this test yet. We might need to add additional validations for EFW, so I'd rather not rush this one. Appreciate your patience on this.

**Comment by annakhm** [comment]
Acceptance test for this will follow shortly.

**Pull request merged**
